services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: staysafe
      POSTGRES_PASSWORD: staysafe
      POSTGRES_DB: staysafe
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      # Fallbacks if not in .env
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://staysafe:staysafe@db:5432/staysafe}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8000:8000"
    depends_on:
      - db
  
volumes:
  pgdata:
